/**
 * Shared fixtures for the Membership & plans root console (stories + tests).
 * Mirrors the backend contract: every plan carries a limit row for each
 * runtime operation, `free`/`plus`/`pro` are the schema defaults, and custom
 * plans are local.
 */
import type {
    MembershipMember,
    MembershipOverviewResponse,
    MembershipPlan,
    MembershipPlanLimit,
} from '@/shared'

export const MEMBERSHIP_OPERATIONS = [
    'ai_card_generation',
    'image_generation',
    'card_image_generation',
    'theme_song_generation',
    'tts_generation',
    'chat_interaction',
    'voice_call',
    'lorebook_resource_extraction',
] as const

export function uniformLimits(
    dailyRequestLimit: number,
    maxInFlight = 1,
    creditCost = 1,
): Record<string, MembershipPlanLimit> {
    return Object.fromEntries(
        MEMBERSHIP_OPERATIONS.map((operation) => [
            operation,
            { daily_request_limit: dailyRequestLimit, max_in_flight: maxInFlight, credit_cost: creditCost },
        ]),
    )
}

export const freePlan: MembershipPlan = {
    plan_code: 'free',
    display_name: 'Free',
    credit_reset_period: 'daily',
    daily_credit_limit: 50,
    is_active: true,
    is_default: true,
    is_billing_synced: false,
    member_count: 128,
    limits: uniformLimits(20, 1, 1),
    created_at: '2026-01-01T00:00:00',
    updated_at: '2026-01-01T00:00:00',
}

export const plusPlan: MembershipPlan = {
    ...freePlan,
    plan_code: 'plus',
    display_name: 'Plus',
    daily_credit_limit: 100,
    is_billing_synced: true,
    member_count: 17,
    limits: uniformLimits(100, 2, 1),
}

export const proPlan: MembershipPlan = {
    ...freePlan,
    plan_code: 'pro',
    display_name: 'Pro',
    daily_credit_limit: 500,
    is_billing_synced: true,
    member_count: 4,
    limits: uniformLimits(500, 4, 1),
}

export const sponsorPlan: MembershipPlan = {
    ...freePlan,
    plan_code: 'sponsor',
    display_name: 'Sponsor',
    daily_credit_limit: 1000,
    is_default: false,
    is_billing_synced: false,
    member_count: 2,
    limits: uniformLimits(800, 4, 1),
    created_at: '2026-06-10T09:30:00',
    updated_at: '2026-06-10T09:30:00',
}

export const retiredPlan: MembershipPlan = {
    ...sponsorPlan,
    plan_code: 'beta-2025',
    display_name: 'Beta 2025',
    daily_credit_limit: 250,
    is_active: false,
    member_count: 0,
    limits: uniformLimits(200, 2, 1),
}

export const plans: MembershipPlan[] = [freePlan, plusPlan, proPlan, sponsorPlan, retiredPlan]

export const members: MembershipMember[] = [
    {
        user_id: 42,
        user_hash: 'usr-lyra-7f3a',
        username: 'lyra',
        display_name: 'Lyra of the Vale',
        user_type: 'consumer',
        created_at: '2026-02-14T10:00:00',
        plan_code: 'pro',
        plan_display_name: 'Pro',
        daily_credit_limit: 500,
        is_default_plan: true,
        implicit_free: false,
        membership_status: 'active',
        started_at: '2026-03-01T12:00:00',
        updated_at: '2026-06-18T08:15:00',
        credits_used_today: 212,
        credits_used_month: 3140,
        included_credits_used_month: 2900,
        payg_credits_used_month: 240,
        payg_free_balance: 40,
        payg_billed_balance: 760,
        payg_balance: 800,
    },
    {
        user_id: 7,
        user_hash: 'usr-root-0001',
        username: 'root',
        display_name: null,
        user_type: 'root',
        created_at: '2026-01-01T00:00:00',
        plan_code: 'sponsor',
        plan_display_name: 'Sponsor',
        daily_credit_limit: 1000,
        is_default_plan: false,
        implicit_free: false,
        membership_status: 'active',
        started_at: '2026-06-10T09:31:00',
        updated_at: '2026-06-10T09:31:00',
        credits_used_today: 12,
        credits_used_month: 380,
        included_credits_used_month: 380,
        payg_credits_used_month: 0,
        payg_free_balance: 0,
        payg_billed_balance: 0,
        payg_balance: 0,
    },
    {
        user_id: 913,
        user_hash: 'usr-newcomer-2b',
        username: 'newcomer',
        display_name: null,
        user_type: 'consumer',
        created_at: '2026-06-19T07:45:00',
        plan_code: 'free',
        plan_display_name: 'Free',
        daily_credit_limit: 50,
        is_default_plan: true,
        implicit_free: true,
        membership_status: 'active',
        started_at: null,
        updated_at: null,
        credits_used_today: 0,
        credits_used_month: 0,
        included_credits_used_month: 0,
        payg_credits_used_month: 0,
        payg_free_balance: 25,
        payg_billed_balance: 0,
        payg_balance: 25,
    },
]

export const overview: MembershipOverviewResponse = {
    usage_date: '2026-06-19',
    month: '2026-06',
    month_start: '2026-06-01',
    month_end: '2026-06-19',
    totals: {
        users: 151,
        plans: 5,
        active_plans: 4,
        custom_plans: 2,
        active_users_today: 38,
        credits_used_today: 1_420,
        active_users_month: 96,
        credits_used_month: 41_300,
        included_credits_used_month: 36_800,
        payg_credits_used_month: 4_500,
        payg_wallets: 63,
        payg_free_balance: 2_150,
        payg_billed_balance: 9_400,
    },
    plans: [
        {
            plan_code: 'free',
            display_name: 'Free',
            is_active: true,
            is_default: true,
            is_billing_synced: false,
            member_count: 128,
            active_users_today: 24,
            credits_used_today: 610,
            active_users_month: 74,
            credits_used_month: 18_200,
            included_credits_used_month: 16_900,
            payg_credits_used_month: 1_300,
        },
        {
            plan_code: 'plus',
            display_name: 'Plus',
            is_active: true,
            is_default: true,
            is_billing_synced: true,
            member_count: 17,
            active_users_today: 9,
            credits_used_today: 380,
            active_users_month: 15,
            credits_used_month: 12_100,
            included_credits_used_month: 10_900,
            payg_credits_used_month: 1_200,
        },
        {
            plan_code: 'pro',
            display_name: 'Pro',
            is_active: true,
            is_default: true,
            is_billing_synced: true,
            member_count: 4,
            active_users_today: 4,
            credits_used_today: 418,
            active_users_month: 4,
            credits_used_month: 9_800,
            included_credits_used_month: 7_800,
            payg_credits_used_month: 2_000,
        },
        {
            plan_code: 'sponsor',
            display_name: 'Sponsor',
            is_active: true,
            is_default: false,
            is_billing_synced: false,
            member_count: 2,
            active_users_today: 1,
            credits_used_today: 12,
            active_users_month: 2,
            credits_used_month: 1_200,
            included_credits_used_month: 1_200,
            payg_credits_used_month: 0,
        },
        {
            plan_code: 'beta-2025',
            display_name: 'Beta 2025',
            is_active: false,
            is_default: false,
            is_billing_synced: false,
            member_count: 0,
            active_users_today: 0,
            credits_used_today: 0,
            active_users_month: 1,
            credits_used_month: 0,
            included_credits_used_month: 0,
            payg_credits_used_month: 0,
        },
    ],
    operations_month: [
        { operation: 'chat_interaction', active_users: 90, used: 21_400, credits_used: 21_400 },
        { operation: 'ai_card_generation', active_users: 41, used: 3_900, credits_used: 3_900 },
        { operation: 'image_generation', active_users: 52, used: 8_200, credits_used: 8_200 },
        { operation: 'card_image_generation', active_users: 30, used: 2_100, credits_used: 2_100 },
        { operation: 'theme_song_generation', active_users: 12, used: 640, credits_used: 640 },
        { operation: 'tts_generation', active_users: 27, used: 3_060, credits_used: 3_060 },
        { operation: 'voice_call', active_users: 5, used: 1_400, credits_used: 1_400 },
        { operation: 'lorebook_resource_extraction', active_users: 9, used: 600, credits_used: 600 },
    ],
}
